# Generated by Django 3.1.3 on 2021-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
