# Generated by Django 3.1.3 on 2021-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
